import os
import re
import uuid
import json
import statistics
from datetime import datetime, timezone
from pathlib import Path
from dotenv import load_dotenv
from groq import Groq
from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address

load_dotenv()
groq_client = Groq(api_key=os.getenv("GROQ_API_KEY"))

AUDIT_LOG = Path("audit_log.jsonl")

def stylometric_score(text: str) -> float:
    sentences = [s.strip() for s in re.split(r'[.!?]+', text) if s.strip()]
    words = re.findall(r'\b\w+\b', text.lower())
    if len(sentences) < 2 or not words:
        return 0.5

    # Low sentence-length variance → uniform → AI-like → score near 1
    sent_lengths = [len(re.findall(r'\b\w+\b', s)) for s in sentences]
    slv = statistics.variance(sent_lengths)
    slv_score = 1 / (1 + slv)

    # Low type-token ratio → repetitive vocabulary → AI-like → score near 1
    ttr_score = 1 - (len(set(words)) / len(words))

    # Low punctuation-count variation across sentences → uniform → AI-like → score near 1
    punct_counts = [len(re.findall(r'[^\w\s]', s)) for s in sentences]
    mean_punct = statistics.mean(punct_counts)
    if mean_punct > 0:
        cv = statistics.stdev(punct_counts) / mean_punct
        punct_score = 1 / (1 + cv)
    else:
        punct_score = 0.5

    return round((slv_score + ttr_score + punct_score) / 3, 4)

def llm_classify(text: str) -> float:
    response = groq_client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "system",
                "content": (
                    "You are an AI-generated text detector. "
                    "Given a passage of text, estimate the probability it was written by an AI (not a human). "
                    "Respond with only a JSON object: {\"ai_probability\": <float between 0.0 and 1.0>}. "
                    "1.0 = certainly AI-generated, 0.0 = certainly human-written."
                ),
            },
            {"role": "user", "content": text},
        ],
        response_format={"type": "json_object"},
        temperature=0,
    )
    result = json.loads(response.choices[0].message.content)
    return round(float(result.get("ai_probability", 0.5)), 4)

def confidence_score(llm_score: float, style_score: float) -> float:
    return round(0.6 * llm_score + 0.4 * style_score, 4)

def attribution_from_confidence(confidence: float) -> str:
    if confidence >= 0.75:
        return "likely_ai"
    if confidence >= 0.40:
        return "uncertain"
    return "likely_human"

def label_from_confidence(confidence: float) -> str:
    pct = f"{round(confidence * 100)}%"
    if confidence >= 0.75:
        return (
            f"This content was likely generated by an AI. Confidence: {pct}. "
            "If you believe this is incorrect, you may submit an appeal."
        )
    if confidence >= 0.40:
        return (
            f"Our system could not confidently determine whether this content is "
            f"human- or AI-written. Confidence: {pct}. No action has been taken."
        )
    return f"This content appears to be human-written. Confidence: {pct}. No action has been taken."

def write_audit(entry: dict):
    with AUDIT_LOG.open("a") as f:
        f.write(json.dumps(entry) + "\n")

def get_log(n: int = 50) -> list:
    if not AUDIT_LOG.exists():
        return []
    lines = AUDIT_LOG.read_text().splitlines()
    return [json.loads(line) for line in lines[-n:]]

def find_submission(content_id: str) -> dict | None:
    if not AUDIT_LOG.exists():
        return None
    for line in AUDIT_LOG.read_text().splitlines():
        entry = json.loads(line)
        if entry.get("content_id") == content_id and entry.get("event") != "appeal":
            return entry
    return None

def update_submission_status(content_id: str, new_status: str):
    lines = AUDIT_LOG.read_text().splitlines()
    updated = []
    for line in lines:
        entry = json.loads(line)
        if entry.get("content_id") == content_id and entry.get("event") != "appeal":
            entry["status"] = new_status
        updated.append(json.dumps(entry))
    AUDIT_LOG.write_text("\n".join(updated) + "\n")

app = Flask(__name__)

@app.route("/")
def home():
    return "Provenance Guard is running."

if __name__ == "__main__":
    app.run(port=5000, debug=True)

@app.route("/submit", methods=["POST"])
def submit():
    data = request.get_json()
    text = data.get("text")
    creator_id = data.get("creator_id")

    content_id = str(uuid.uuid4())
    llm_score = llm_classify(text)
    style_score = stylometric_score(text)
    confidence = confidence_score(llm_score, style_score)
    attribution = attribution_from_confidence(confidence)

    write_audit({
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "style_score": style_score,
        "status": "classified",
    })

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "label": label_from_confidence(confidence),
    })

@app.route("/log", methods=["GET"])
def log():
    return jsonify({"entries": get_log()})

@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json()
    content_id = data.get("content_id")
    explanation = data.get("explanation", "")

    if not content_id:
        return jsonify({"error": "content_id is required"}), 400

    submission = find_submission(content_id)
    if not submission:
        return jsonify({"error": "Submission not found"}), 404

    if submission.get("attribution") != "likely_ai":
        return jsonify({"error": "Appeals are only available for likely_ai submissions"}), 403

    update_submission_status(content_id, "under_review")
    write_audit({
        "event": "appeal",
        "content_id": content_id,
        "explanation": explanation,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "status": "under_review",
    })

    return jsonify({
        "content_id": content_id,
        "status": "under_review",
        "message": "Your appeal was received and is under review.",
    })
limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)